# Gopkg.toml
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

# Historically, loki had a dependency on tomwilkie/prometheus#scrape-callback
# but the branch was eventually deleted from the repository, which led to
# issues when updating/changing dependencies. This branch was therefore recreated
# under weaveworks-experiments/prometheus and should be used as a dependency for loki,
# hence the below constraint.
# Should prometheus be upgraded, the diff applied on the closest upstream can be found here:
# https://github.com/weaveworks-experiments/prometheus/commit/d8d2921c4933f770e2638586a54da5840aee3d0d
[[constraint]]
  name = "github.com/prometheus/prometheus"
  source = "github.com/weaveworks-experiments/prometheus"
  branch = "scrape-callback"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "8a25372bbfec739b8719a9e3987400d15ef9e179"

[[override]]
  name = "github.com/ugorji/go"
  revision = "708a42d246822952f38190a8d8c4e6b16a0e600c"

[[override]]
  name = "github.com/apache/thrift"
  branch = "master"
